# shellcheck shell=bash
# Shared dev setup helpers for start-dev.sh (interactive Easy vs Custom).

dev_detect_lan_ip() {
  local ip=""
  ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  if [[ -z "${ip:-}" ]] && command -v ip >/dev/null 2>&1; then
    ip="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}' || true)"
  fi
  if [[ -z "${ip:-}" ]] && command -v ipconfig >/dev/null 2>&1; then
    ip="$(ipconfig 2>/dev/null | awk '/IPv4 Address/ {print $NF; exit}' | tr -d '\r' || true)"
  fi
  [[ -n "${ip:-}" ]] && echo "$ip"
}

dev_is_interactive() {
  [[ -t 0 ]] && [[ -z "${SQL_OPTIMA_SETUP_MODE:-}" ]]
}

dev_prompt_default() {
  local prompt="$1" default="$2" out_var="$3"
  local input=""
  read -r -p "${prompt} [${default}]: " input
  if [[ -z "${input:-}" ]]; then
    printf -v "$out_var" '%s' "$default"
  else
    printf -v "$out_var" '%s' "$input"
  fi
}

dev_prompt_yes_no() {
  local prompt="$1" default_no="$2" out_var="$3"
  local input="" default_yn="N"
  [[ "$default_no" != "1" ]] && default_yn="Y"
  read -r -p "${prompt} [y/N]: " input
  input="$(echo "${input:-}" | tr '[:upper:]' '[:lower:]')"
  if [[ -z "$input" ]]; then
    if [[ "$default_no" == "1" ]]; then
      printf -v "$out_var" '0'
    else
      printf -v "$out_var" '1'
    fi
    return 0
  fi
  case "$input" in
    y|yes) printf -v "$out_var" '1' ;;
    *) printf -v "$out_var" '0' ;;
  esac
}

dev_resolve_setup() {
  # Outputs via globals: DEV_SETUP_MODE DEV_EXPOSE_LAN DEV_DB_USER DEV_DB_PASSWORD
  # DEV_DB_NAME DEV_API_PORT DEV_DB_PUBLISH_PORT DEV_DB_PUBLISH_BIND
  DEV_SETUP_MODE="${SQL_OPTIMA_SETUP_MODE:-easy}"
  DEV_EXPOSE_LAN="${SQL_OPTIMA_EXPOSE_DB_LAN:-0}"
  DEV_DB_USER="${SQL_OPTIMA_DB_USER:-dbmonitor}"
  DEV_DB_PASSWORD="${SQL_OPTIMA_DB_PASSWORD:-sql_optima_dev_local_only}"
  DEV_DB_NAME="${SQL_OPTIMA_DB_NAME:-dbmonitor_metrics}"
  DEV_API_PORT="${SQL_OPTIMA_API_PORT:-8080}"
  DEV_DB_PUBLISH_PORT="${SQL_OPTIMA_DB_PUBLISH_PORT:-5432}"
  DEV_DB_PUBLISH_BIND="${SQL_OPTIMA_DB_PUBLISH_BIND:-}"

  if dev_is_interactive; then
    echo ""
    echo "SQL Optima Dev Setup"
    echo "Choose configuration:"
    echo "  1) Easy setup (safe): Local-only DB. No LAN/DBeaver access to TimescaleDB."
    echo "  2) Custom setup: Configure credentials and optionally enable LAN/DBeaver access."
    echo ""
    local choice=""
    dev_prompt_default "Enter 1 or 2" "1" choice
    case "$choice" in
      2) DEV_SETUP_MODE="custom" ;;
      *) DEV_SETUP_MODE="easy" DEV_EXPOSE_LAN=0 ;;
    esac
  fi

  if [[ "$DEV_SETUP_MODE" == "easy" ]]; then
    DEV_EXPOSE_LAN=0
    if dev_is_interactive; then
      echo ""
      echo "Easy setup selected."
      echo "Starting the dev stack with safe defaults..."
    fi
    return 0
  fi

  if dev_is_interactive; then
    echo ""
    echo "Custom setup selected."
    echo ""
    echo "TimescaleDB (monitoring DB) defaults:"
    echo "  DB name   [${DEV_DB_NAME}]"
    echo "  DB user   [${DEV_DB_USER}]"
    echo "  (Press Enter to keep defaults.)"
    echo ""
    dev_prompt_default "DB name" "$DEV_DB_NAME" DEV_DB_NAME
    dev_prompt_default "DB user" "$DEV_DB_USER" DEV_DB_USER
    echo -n "DB password (hidden, Enter for default): "
    local pw=""
    read -rs pw
    echo ""
    [[ -n "${pw:-}" ]] && DEV_DB_PASSWORD="$pw"
    echo ""
    dev_prompt_default "API server port (API_PORT)" "$DEV_API_PORT" DEV_API_PORT
    echo ""
    echo "Enable LAN/DBeaver access to the monitoring DB?"
    echo "  This publishes the DB port so other machines on your LAN can connect."
    echo "  Bind scope: LAN-only (host LAN IP)."
    dev_prompt_yes_no "Enable LAN?" 1 DEV_EXPOSE_LAN
    if [[ "$DEV_EXPOSE_LAN" == "1" ]]; then
      dev_prompt_default "Publish port on host" "$DEV_DB_PUBLISH_PORT" DEV_DB_PUBLISH_PORT
    fi
  fi

  if [[ "$DEV_EXPOSE_LAN" == "1" ]]; then
    if [[ -z "${DEV_DB_PUBLISH_BIND:-}" ]]; then
      DEV_DB_PUBLISH_BIND="$(dev_detect_lan_ip || true)"
    fi
    if [[ -z "${DEV_DB_PUBLISH_BIND:-}" ]]; then
      echo "[sql-optima] ERROR: Could not detect LAN IP for DB publish bind." >&2
      echo "[sql-optima] Set SQL_OPTIMA_DB_PUBLISH_BIND to your host LAN address and retry." >&2
      exit 1
    fi
  fi
}

dev_write_env_file() {
  local target="${1:-.env}"
  cat >"$target" <<EOF
# Generated by start-dev.sh - dev evaluation only (not for production).
DB_USER=${DEV_DB_USER}
DB_PASSWORD=${DEV_DB_PASSWORD}
DB_NAME=${DEV_DB_NAME}

API_PORT=${DEV_API_PORT}

AUTH_REQUIRED=1
DISABLE_PUBLIC_SETUP=0
JWT_SECRET=sql-optima-local-dev-jwt-secret-32chars-min

VAULT_TRANSIT_KEY=sql-optima

COLD_STORAGE_ENABLED=false
COLD_STORAGE_SECRET_ACCESS_KEY=${DEV_DB_PASSWORD}

SQL_OPTIMA_SETUP_MODE=${DEV_SETUP_MODE}
SQL_OPTIMA_EXPOSE_DB_LAN=${DEV_EXPOSE_LAN}
EOF
  if [[ "$DEV_EXPOSE_LAN" == "1" ]]; then
    cat >>"$target" <<EOF

COMPOSE_FILE=docker-compose.yml:docker-compose.dev.yml
DB_PUBLISH_PORT=${DEV_DB_PUBLISH_PORT}
DB_PUBLISH_BIND=${DEV_DB_PUBLISH_BIND}
EOF
  fi
}

dev_env_expose_lan() {
  local v
  v="$(grep -E '^[[:space:]]*SQL_OPTIMA_EXPOSE_DB_LAN=' .env 2>/dev/null | tail -1 | cut -d= -f2- | tr -d '\r ' || true)"
  [[ "$v" == "1" ]] && return 0
  grep -qE 'docker-compose\.dev\.yml' .env 2>/dev/null && return 0
  return 1
}
