{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timescaledb.secretName" . }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.existingSecretPasswordKey }}: {{ required "timescaledb.auth.password or timescaledb.auth.existingSecret is required" .Values.auth.password | quote }}
{{- end }}
