/*
COMPREHENSIVE RULE ENGINE FIX
Fixed detection_sql, evaluation_logic, and expected_calc for all rules
*/

-- First add missing columns to the existing rules table
ALTER TABLE ruleengine.rules ADD COLUMN IF NOT EXISTS comparison_type VARCHAR(20) DEFAULT 'exact';
ALTER TABLE ruleengine.rules ADD COLUMN IF NOT EXISTS threshold_value JSONB;
ALTER TABLE ruleengine.rules ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 0;

-- Clear existing rules for fresh start
DELETE FROM ruleengine.rule_results_evaluated;
DELETE FROM ruleengine.rule_results_raw;
DELETE FROM ruleengine.rule_runs;
DELETE FROM ruleengine.rules;

-- Insert SQL Server Rules with proper expressions
INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('INST_MEM_MAX_001','Max Server Memory','Instance Config','Instance','Critical','Main','SQL Server consuming all RAM causes OS starvation.','SELECT total_physical_memory_kb/1024/1024 AS TotalRAM_GB, CAST(value_in_use AS BIGINT) AS MaxServerMemoryMB FROM sys.configurations CROSS JOIN sys.dm_os_sys_memory WHERE name=''max server memory (MB)'';',NULL,'MaxServerMemoryMB >= 2147483647 ? "Critical" : (MaxServerMemoryMB < Recommended ? "Warning" : "OK")','(TotalRAM_GB <= 16 ? TotalRAM_GB - 4 : (TotalRAM_GB <= 32 ? TotalRAM_GB - 6 : (TotalRAM_GB <= 64 ? TotalRAM_GB - 8 : (TotalRAM_GB <= 128 ? TotalRAM_GB - 12 : (TotalRAM_GB <= 256 ? TotalRAM_GB - 16 : TotalRAM_GB - 32))))) * 1024','TotalRAM - OS Reserve','EXEC sp_configure ''max server memory (MB)'', <RecommendedMB>; RECONFIGURE;',NULL,'threshold','{"unit":"MB"}',1,'sqlserver',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('INST_CPU_MAXDOP_003','MAXDOP Setting','Parallelism','Instance','Critical','Main','Wrong MAXDOP causes CXPACKET waits.','SELECT cpu_count, (SELECT CAST(value_in_use AS INT) FROM sys.configurations WHERE name=''max degree of parallelism'') AS MAXDOP FROM sys.dm_os_sys_info;',NULL,'MAXDOP <= 0 ? "Critical" : (MAXDOP > 8 ? "Warning" : "OK")','cpu_count > 8 ? 8 : cpu_count','<=8 CPUs else 8','EXEC sp_configure ''max degree of parallelism'', <Value>; RECONFIGURE;',NULL,'range','{"min":1,"max":8}',2,'sqlserver',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('INST_CPU_CTFP_004','Cost Threshold for Parallelism','Parallelism','Instance','Critical','Main','Default value 5 is too low for modern servers.','SELECT CAST(value_in_use AS INT) AS value_in_use FROM sys.configurations WHERE name=''cost threshold for parallelism'';',NULL,'value_in_use < 50 ? "Warning" : "OK"','50','50','EXEC sp_configure ''cost threshold for parallelism'',50; RECONFIGURE;',NULL,'threshold','{"min":50}',3,'sqlserver',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('INST_PLAN_CACHE_005','Optimize for AdHoc Workloads','Plan Cache','Instance','Critical','Main','Prevents plan cache bloat.','SELECT CAST(value_in_use AS INT) AS value_in_use FROM sys.configurations WHERE name=''optimize for ad hoc workloads'';',NULL,'value_in_use == 1 ? "OK" : "Warning"','1','1 (enabled)','EXEC sp_configure ''optimize for ad hoc workloads'',1; RECONFIGURE;',NULL,'exact','{"value":1}',4,'sqlserver',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('INST_IFI_006','Instant File Initialization','Storage','OS','Critical','Main','Database growth freezes server without IFI.','SELECT CAST(instant_file_initialization_enabled AS INT) AS instant_file_initialization_enabled FROM sys.dm_server_services;',NULL,'instant_file_initialization_enabled == 1 ? "OK" : "Critical"','1','1 (enabled)','Grant Perform Volume Maintenance Tasks to SQL Service Account',NULL,'exact','{"value":1}',5,'sqlserver',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('DB_AUTOSHRINK_007','Auto Shrink Enabled','Database Config','Database','Critical','Main','Causes fragmentation and performance issues.','SELECT CAST(ISNULL((SELECT TOP 1 is_auto_shrink_on FROM sys.databases WHERE database_id = DB_ID()), 0) AS INT) AS is_auto_shrink_on;',NULL,'is_auto_shrink_on == 1 ? "Critical" : "OK"','0','OFF','ALTER DATABASE SET AUTO_SHRINK OFF;',NULL,'exact','{"value":0}',6,'sqlserver',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('DB_AUTOCLOSE_008','Auto Close Enabled','Database Config','Database','Critical','Main','Causes connection latency.','SELECT CAST(ISNULL((SELECT TOP 1 is_auto_close_on FROM sys.databases WHERE database_id = DB_ID()), 0) AS INT) AS is_auto_close_on;',NULL,'is_auto_close_on == 1 ? "Critical" : "OK"','0','OFF','ALTER DATABASE SET AUTO_CLOSE OFF;',NULL,'exact','{"value":0}',7,'sqlserver',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('TEMPDB_FILECOUNT_009','TempDB File Count','TempDB','TempDB','Critical','Main','Improper TempDB layout causes PAGELATCH waits.','SELECT CAST(COUNT(*) AS INT) AS file_count FROM sys.master_files WHERE database_id=2 AND type_desc=''ROWS'';',NULL,'file_count == 0 ? "Critical" : (file_count > 8 ? "Warning" : "OK")','4','4 or CPU/4','Manual TempDB reconfiguration required',NULL,'range','{"min":4,"max":8}',8,'sqlserver',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('BACKUP_LOG_010','Log Backup Recent','Backup','Database','Critical','Main','Missing log backups break point-in-time recovery.','SELECT CAST(ISNULL(DATEDIFF(MINUTE, (SELECT MAX(backup_finish_date) FROM msdb.dbo.backupset WHERE type = ''L''), GETDATE()), 9999) AS INT) AS minutes_since_log_backup;',NULL,'minutes_since_log_backup > 60 ? "Critical" : (minutes_since_log_backup > 15 ? "Warning" : "OK")','15','< 15 minutes','Create SQL Agent log backup job',NULL,'threshold','{"max":15}',9,'sqlserver',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('QUERY_STORE_011','Query Store Enabled','Monitoring','Database','Critical','Main','Query Store provides performance insights.','SELECT CAST(ISNULL((SELECT TOP 1 is_query_store_on FROM sys.databases WHERE database_id = DB_ID()), 0) AS INT) AS is_query_store_on;',NULL,'is_query_store_on == 1 ? "OK" : "Warning"','1','ON','ALTER DATABASE SET QUERY_STORE ON;',NULL,'exact','{"value":1}',10,'sqlserver',TRUE);

-- PostgreSQL Rules
INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('PG_SHARED_BUFFERS_001','Shared Buffers','Memory','Instance','Critical','Main','PostgreSQL shared_buffers at default 128MB is too low.','SELECT setting::bigint AS setting FROM pg_settings WHERE name = ''shared_buffers'';','SELECT setting::bigint AS setting FROM pg_settings WHERE name = ''shared_buffers'';','setting < 131072 ? "Critical" : (setting < 262144 ? "Warning" : "OK")','262144','256MB','ALTER SYSTEM SET shared_buffers = ''256MB'';','ALTER SYSTEM SET shared_buffers = ''256MB'';','threshold','{"min":262144}',1,'postgres',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('PG_MAX_CONNECTIONS_001','Max Connections','Connection','Instance','Warning','BestPractice','High connections consume memory.','SELECT setting::int AS setting FROM pg_settings WHERE name = ''max_connections'';','SELECT setting::int AS setting FROM pg_settings WHERE name = ''max_connections'';','setting > 500 ? "Warning" : "OK"','100','100','ALTER SYSTEM SET max_connections = ''100'';','ALTER SYSTEM SET max_connections = ''100'';','threshold','{"max":500}',2,'postgres',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('PG_WORK_MEM_001','Work Mem','Memory','Instance','Warning','BestPractice','Complex sorts spill to disk at default 4MB.','SELECT setting::bigint AS setting FROM pg_settings WHERE name = ''work_mem'';','SELECT setting::bigint AS setting FROM pg_settings WHERE name = ''work_mem'';','setting < 256 ? "Warning" : "OK"','256','256MB','ALTER SYSTEM SET work_mem = ''256MB'';','ALTER SYSTEM SET work_mem = ''256MB'';','threshold','{"min":256}',3,'postgres',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('PG_MAINT_WORK_MEM_001','Maintenance Work Mem','Maintenance','Instance','Warning','BestPractice','VACUUM and CREATE INDEX are slow at default 64MB.','SELECT setting::bigint AS setting FROM pg_settings WHERE name = ''maintenance_work_mem'';','SELECT setting::bigint AS setting FROM pg_settings WHERE name = ''maintenance_work_mem'';','setting < 512 ? "Warning" : "OK"','512','512MB','ALTER SYSTEM SET maintenance_work_mem = ''512MB'';','ALTER SYSTEM SET maintenance_work_mem = ''512MB'';','threshold','{"min":512}',4,'postgres',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('PG_RANDOM_PAGE_COST_001','Random Page Cost','Performance','Instance','Warning','BestPractice','Default 4.0 is for HDD, not SSD.','SELECT setting::float8 AS setting FROM pg_settings WHERE name = ''random_page_cost'';','SELECT setting::float8 AS setting FROM pg_settings WHERE name = ''random_page_cost'';','setting > 1.5 ? "Warning" : "OK"','1.1','1.1 (SSD)','ALTER SYSTEM SET random_page_cost = ''1.1'';','ALTER SYSTEM SET random_page_cost = ''1.1'';','threshold','{"max":1.1}',5,'postgres',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('PG_EFFECTIVE_CACHE_SIZE_001','Effective Cache Size','Performance','Instance','Warning','BestPractice','Default 4GB is too low for modern servers.','SELECT setting::bigint AS setting FROM pg_settings WHERE name = ''effective_cache_size'';','SELECT setting::bigint AS setting FROM pg_settings WHERE name = ''effective_cache_size'';','setting < 8388608 ? "Warning" : "OK"','8388608','8GB','ALTER SYSTEM SET effective_cache_size = ''8GB'';','ALTER SYSTEM SET effective_cache_size = ''8GB'';','threshold','{"min":8388608}',6,'postgres',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('PG_CHKPT_COMPLETE_TARGET_001','Checkpoint Completion Target','Performance','Instance','Warning','BestPractice','Low target causes I/O spikes.','SELECT setting::float8 AS setting FROM pg_settings WHERE name = ''checkpoint_completion_target'';','SELECT setting::float8 AS setting FROM pg_settings WHERE name = ''checkpoint_completion_target'';','setting < 0.9 ? "Warning" : "OK"','0.9','0.9','ALTER SYSTEM SET checkpoint_completion_target = ''0.9'';','ALTER SYSTEM SET checkpoint_completion_target = ''0.9'';','threshold','{"min":0.9}',7,'postgres',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('PG_WAL_BUFFERS_001','WAL Buffers','Performance','Instance','Warning','BestPractice','Low WAL buffers causes frequent flushes.','SELECT setting::bigint AS setting FROM pg_settings WHERE name = ''wal_buffers'';','SELECT setting::bigint AS setting FROM pg_settings WHERE name = ''wal_buffers'';','setting < 16 ? "Warning" : "OK"','16','16MB','ALTER SYSTEM SET wal_buffers = ''16MB'';','ALTER SYSTEM SET wal_buffers = ''16MB'';','threshold','{"min":16}',8,'postgres',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('PG_DEAD_TUPLES_001','Dead Tuple Ratio','Maintenance','Database','Critical','Main','High dead tuples indicate autovacuum issues.','SELECT n_dead_tup, n_live_tup, CASE WHEN n_live_tup > 0 THEN (n_dead_tup::float / n_live_tup) * 100 ELSE 0 END AS dead_pct FROM pg_stat_user_tables WHERE n_dead_tup > 1000 ORDER BY n_dead_tup DESC LIMIT 1;','SELECT n_dead_tup, n_live_tup, CASE WHEN n_live_tup > 0 THEN (n_dead_tup::float / n_live_tup) * 100 ELSE 0 END AS dead_pct FROM pg_stat_user_tables WHERE n_dead_tup > 1000 ORDER BY n_dead_tup DESC LIMIT 1;','dead_pct > 20 ? "Critical" : (dead_pct > 10 ? "Warning" : "OK")','10','< 10%','VACUUM ANALYZE;',NULL,'threshold','{"max":10}',9,'postgres',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('PG_REPL_LAG_001','Replication Lag','High Availability','Instance','Critical','Main','Standby falling behind risks data loss.','SELECT COALESCE(pg_wal_lsn_diff(pg_current_wal_lsn(), replay_lsn), 0) AS lag_bytes FROM pg_stat_replication LIMIT 1;','SELECT COALESCE(pg_wal_lsn_diff(pg_current_wal_lsn(), replay_lsn), 0) AS lag_bytes FROM pg_stat_replication LIMIT 1;','lag_bytes > 52428800 ? "Critical" : (lag_bytes > 10485760 ? "Warning" : "OK")','0','0 bytes','Check network/IO on standby',NULL,'threshold','{"max":0}',10,'postgres',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('PG_STAT_STMTS_001','pg_stat_statements','Monitoring','Instance','Critical','BestPractice','Extension needed for query analysis.','SELECT COUNT(*) AS cnt FROM pg_extension WHERE extname = ''pg_stat_statements'';','SELECT COUNT(*) AS cnt FROM pg_extension WHERE extname = ''pg_stat_statements'';','cnt > 0 ? "OK" : "Critical"','1','Installed','CREATE EXTENSION pg_stat_statements;',NULL,'exact','{"value":1}',11,'postgres',TRUE);

INSERT INTO ruleengine.rules (rule_id, rule_name, category, applies_to, severity, dashboard_placement, description, detection_sql, detection_sql_pg, evaluation_logic, expected_calc, recommended_value, fix_script, fix_script_pg, comparison_type, threshold_value, priority, target_db_type, is_enabled) VALUES
('PG_IDLE_TX_001','Idle in Transaction','Connection','Instance','Critical','Main','Long idle transactions block VACUUM.','SELECT COUNT(*) AS cnt FROM pg_stat_activity WHERE state = ''idle in transaction'' AND state_change < current_timestamp - interval ''5 minutes'';','SELECT COUNT(*) AS cnt FROM pg_stat_activity WHERE state = ''idle in transaction'' AND state_change < current_timestamp - interval ''5 minutes'';','cnt > 0 ? "Warning" : "OK"','0','0','Set idle_in_transaction_session_timeout',NULL,'threshold','{"max":0}',12,'postgres',TRUE);

-- Verify rules
SELECT rule_id, rule_name, target_db_type, evaluation_logic, expected_calc FROM ruleengine.rules ORDER BY target_db_type, rule_id;