#!/usr/bin/env bash
set -euo pipefail

COMPOSE_FILE="${COMPOSE_FILE:-docker/docker-compose.yml}"
CONFIG_PATH="${CONFIG_PATH:-config.yaml}"
ENV_FILE="${ENV_FILE:-docker/.env.local}"
NO_BUILD="${NO_BUILD:-0}"

to_env_key() {
  local name="$1"
  local suffix="$2"
  local k
  k="$(echo "$name" | tr '[:lower:]' '[:upper:]' | tr '-' '_')"
  echo "DB_${k}_${suffix}"
}

instance_names_from_config() {
  # Extract values from lines like: - name: "SQL-Local" OR - name: SQL-Local
  sed -nE 's/^[[:space:]]*-[[:space:]]*name:[[:space:]]*"?([^"#]+)"?[[:space:]]*$/\1/p' "$CONFIG_PATH" | awk '{$1=$1};1' | awk '!seen[$0]++'
}

read_env_value() {
  local key="$1"
  [[ -f "$ENV_FILE" ]] || return 1
  # read last occurrence of KEY=... (ignore comments/blank)
  awk -F= -v k="$key" '
    $0 ~ /^[[:space:]]*#/ { next }
    NF >= 2 {
      kk=$1
      sub(/^[[:space:]]+/, "", kk); sub(/[[:space:]]+$/, "", kk)
      if (kk == k) {
        vv=substr($0, index($0, "=")+1)
        print vv
      }
    }
  ' "$ENV_FILE" | tail -n 1
}

echo "SQL Optima setup (Linux/macOS)"
echo "- config: $CONFIG_PATH"
echo "- compose: $COMPOSE_FILE"
echo "- env file: $ENV_FILE"

if [[ ! -f "$CONFIG_PATH" ]]; then
  echo "config not found: $CONFIG_PATH" >&2
  exit 1
fi

mapfile -t INSTANCES < <(instance_names_from_config)
if [[ ${#INSTANCES[@]} -eq 0 ]]; then
  echo "No instances found in $CONFIG_PATH (add entries under 'instances:')" >&2
  exit 1
fi

mkdir -p "$(dirname "$ENV_FILE")"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
{
  echo "# Generated by scripts/setup.sh on $(date -Is)"
  echo "# Do not commit this file."
  echo ""
} > "$tmp"

for inst in "${INSTANCES[@]}"; do
  echo ""
  echo "Instance: $inst"
  user_key="$(to_env_key "$inst" "USER")"
  pass_key="$(to_env_key "$inst" "PASSWORD")"

  existing_user="$(read_env_value "$user_key" || true)"
  existing_pass="$(read_env_value "$pass_key" || true)"
  if [[ -n "${existing_user}" && -n "${existing_pass}" ]]; then
    echo "  Using existing credentials from $ENV_FILE"
    echo "${user_key}=${existing_user}" >> "$tmp"
    echo "${pass_key}=${existing_pass}" >> "$tmp"
    continue
  fi

  read -r -p "  Username (leave blank to skip this instance): " user
  if [[ -z "${user// }" ]]; then
    echo "  Skipping $inst (no username provided)"
    continue
  fi
  read -r -s -p "  Password: " pass
  echo ""

  echo "${user_key}=${user}" >> "$tmp"
  echo "${pass_key}=${pass}" >> "$tmp"
done

mv "$tmp" "$ENV_FILE"
chmod 600 "$ENV_FILE" 2>/dev/null || true

echo ""
echo "Wrote $ENV_FILE"
echo "Starting docker compose..."

build_flag=""
if [[ "$NO_BUILD" != "1" ]]; then
  build_flag="--build"
fi

docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d $build_flag

echo ""
echo "Status:"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" ps

echo ""
echo "Tip: tail logs with:"
echo "  docker compose --env-file \"$ENV_FILE\" -f \"$COMPOSE_FILE\" logs -f api"

