param(
  [switch]$NoBuild,
  [string]$ComposeFile = "docker/docker-compose.yml",
  [string]$ConfigPath = "config.yaml",
  [string]$EnvFile = "docker/.env.local"
)

$ErrorActionPreference = "Stop"

function ToEnvKey([string]$instanceName, [string]$suffix) {
  $k = ($instanceName.Trim().ToUpper() -replace "-", "_")
  return "DB_{0}_{1}" -f $k, $suffix
}

function GetInstanceNamesFromConfig([string]$path) {
  if (!(Test-Path $path)) {
    throw "config not found: $path"
  }
  $names = @()
  foreach ($line in Get-Content -LiteralPath $path) {
    # match: - name: "SQL-Local"  OR  - name: SQL-Local
    if ($line -match '^\s*-\s*name:\s*"?([^"#]+?)"?\s*$') {
      $n = $Matches[1].Trim()
      if ($n -and ($names -notcontains $n)) {
        $names += $n
      }
    }
  }
  return $names
}

function ReadEnvFile([string]$path) {
  $m = @{}
  if (!(Test-Path $path)) {
    return $m
  }
  foreach ($line in Get-Content -LiteralPath $path) {
    $t = $line.Trim()
    if ($t -eq "" -or $t.StartsWith("#")) { continue }
    $idx = $t.IndexOf("=")
    if ($idx -le 0) { continue }
    $k = $t.Substring(0, $idx).Trim()
    $v = $t.Substring($idx + 1)
    if ($k -ne "") {
      $m[$k] = $v
    }
  }
  return $m
}

Write-Host "SQL Optima setup (Windows)"
Write-Host "- config: $ConfigPath"
Write-Host "- compose: $ComposeFile"
Write-Host "- env file: $EnvFile"

$instances = GetInstanceNamesFromConfig $ConfigPath
if ($instances.Count -eq 0) {
  throw "No instances found in $ConfigPath (add entries under 'instances:')"
}

$outDir = Split-Path -Parent $EnvFile
if ($outDir -and !(Test-Path $outDir)) {
  New-Item -ItemType Directory -Path $outDir | Out-Null
}

$existing = ReadEnvFile $EnvFile

# Build .env.local content in-memory (avoid partial writes).
$lines = @()
$lines += "# Generated by scripts/setup.ps1 on $(Get-Date -Format s)"
$lines += "# Do not commit this file."
$lines += ""

foreach ($inst in $instances) {
  Write-Host ""
  Write-Host "Instance: $inst"

  $userKey = ToEnvKey $inst "USER"
  $passKey = ToEnvKey $inst "PASSWORD"

  if ($existing.ContainsKey($userKey) -and $existing.ContainsKey($passKey) -and
      -not [string]::IsNullOrWhiteSpace([string]$existing[$userKey]) -and
      -not [string]::IsNullOrWhiteSpace([string]$existing[$passKey])) {
    Write-Host "  Using existing credentials from $EnvFile"
    $lines += "$userKey=$($existing[$userKey])"
    $lines += "$passKey=$($existing[$passKey])"
    continue
  }

  $user = Read-Host "  Username (leave blank to skip this instance, or press Enter to keep prompting next)"
  if ([string]::IsNullOrWhiteSpace($user)) {
    Write-Host "  Skipping $inst (no username provided)"
    continue
  }

  $secure = Read-Host "  Password" -AsSecureString
  $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
  try {
    $pass = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
  } finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
  }

  $lines += "$userKey=$user"
  $lines += "$passKey=$pass"
}

Set-Content -LiteralPath $EnvFile -Value $lines -Encoding UTF8
Write-Host ""
Write-Host "Wrote $EnvFile"
Write-Host "Starting docker compose..."

$buildArg = "--build"
if ($NoBuild.IsPresent) {
  $buildArg = ""
}
docker compose --env-file $EnvFile -f $ComposeFile up -d $buildArg

Write-Host ""
Write-Host "Status:"
docker compose --env-file $EnvFile -f $ComposeFile ps

Write-Host ""
Write-Host "Tip: tail logs with:"
Write-Host "  docker compose --env-file $EnvFile -f $ComposeFile logs -f api"

