connector.name=iceberg
iceberg.catalog.type=nessie
iceberg.nessie.uri=http://nessie:19120/api/v1
iceberg.nessie.ref=main
hive.s3.endpoint=http://minio:9000
hive.s3.aws-access-key=sqloptima
hive.s3.aws-secret-key=change_me_in_production
hive.s3.path-style-access=true
hive.s3.ssl.enabled=false
